export const UNITS = [
  'ARARAQUARA',
  'BARRA',
  'BENALCOOL',
  'BONFIM',
  'CAARAPÓ',
  'CONTINENTAL',
  'COSTA PINTO',
  'DESTIVALE',
  'DIAMANTE',
  'DOIS CÓRREGOS (Hibernada)',
  'GASA',
  'IPAUSSÚ',
  'JARDEST (Hibernada)',
  'JATAÍ',
  'JUNQUEIRA',
  'LAGOA DA PRATA',
  'LEME',
  'MARACAÍ',
  'MARACAJU (Hibernada)',
  'MB (Hibernada)',
  'MUNDIAL',
  'PARAGUAÇU',
  'PARAÍSO',
  'PASSA TEMPO',
  'RAFARD',
  'RIO BRILHANTE',
  'SANTA CÂNDIDA',
  'SANTA ELISA',
  'SANTA HELENA (Hibernada)',
  'SÃO FRANCISCO',
  'SERRA',
  'TAMOIO (Hibernada)',
  'TARUMÃ',
  'UNIVALEM',
  'VALE DO ROSÁRIO'
]; 